# Generated by Django 5.0.7 on 2024-08-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('ethnicity', models.IntegerField()),
                ('paramental_education', models.IntegerField()),
                ('study_time_weekly', models.FloatField()),
                ('absenses', models.IntegerField()),
                ('tutoring', models.IntegerField()),
                ('parental_suporte', models.IntegerField()),
                ('extracurricular', models.IntegerField()),
                ('sports', models.IntegerField()),
                ('music', models.IntegerField()),
                ('voluteering', models.IntegerField()),
                ('gpa', models.FloatField()),
            ],
            options={
                'db_table': 'student_performance',
            },
        ),
    ]
