# Generated by Django 5.0.7 on 2024-08-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='grade_class',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
